[Tron-1] added startup menu (HI)
sw19-tug/SPbPU2019 pull request #72
Opened 2019-11-21 09:46 UTC by DGSR

Implemented basic structure based on Minesweeper main menu
And added some styles

2019-11-21 14:58 UTC, rs1t commented
Awesome design 👍

2019-11-21 15:01 UTC, rs1t requested changes
How about storing images in a separate folder?

2019-11-21 15:44 UTC, DGSR commented
@rs1t Done as suggested

2019-11-21 15:56 UTC, rs1t approved these changes

2019-11-21 19:10 UTC, DariaKapustina approved these changes

2019-11-22 14:47 UTC, motya-not-dev approved these changes

2019-11-22 14:47 UTC, Ikhsanovak commented on Tron/gameField.html
> +    <title>Minesweeper</title>
Change title, please

2019-11-22 14:49 UTC, merged