[Tron-2] changed movement logic (HI)
sw19-tug/SPbPU2019 pull request #88
Opened 2019-11-28 13:33 UTC by DGSR

This one is pretty big, so check carefully
I will await at least 3 approves
Closes #14 
Closes #15 
Closes #17 
Closes #16

2019-11-29 20:41 UTC, motya-not-dev approved these changes

2019-11-29 20:44 UTC, DariaKapustina approved these changes

2019-11-30 20:02 UTC, rs1t requested changes

2019-11-30 20:02 UTC, rs1t commented on Tron/TronJS.js
> +        };
`;` is not needed after `}` in `for`, `function` , `switch` blocks

2019-11-30 20:02 UTC, rs1t commented on Tron/TronJS.js
> +            if (player.direction !== 'DOWN') {
I think it would be better to extract these constants like this:
```
const Direction = {
    UP: 1,
    DOWN: 2,
    LEFT: 3,
    RIGHT: 4,
};
```
and use them everywhere:
```
if (player.direction !== Direction.DOWN) {
```

2019-12-01 13:21 UTC, DGSR commented on Tron/TronJS.js
> +        };
Done as suggested

2019-12-01 13:22 UTC, DGSR commented on Tron/TronJS.js
> +            if (player.direction !== 'DOWN') {
Done as suggested

2019-12-01 13:25 UTC, rs1t approved these changes

2019-12-01 13:26 UTC, merged